# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
# tasks:
#   - name: Script Task
#     init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#     command: echo 'start script'

      
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart



#############################################################################################################
#############################################################################################################
#                                         My Configuration  
#############################################################################################################
#############################################################################################################
tasks:
  - name: utils
    before: |
      sudo apt update
      sudo apt install tree  
    
  - name: powershell
    before: |
      # Update the package list
      sudo apt update
      
      # Install prerequisites
      sudo apt install -y wget apt-transport-https software-properties-common
      
      # Download and install the Microsoft GPG key
      wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
      sudo dpkg -i packages-microsoft-prod.deb
      
      # Update the package list again
      sudo apt update
      
      # Install PowerShell
      sudo apt install -y powershell

      # Clean up
      rm packages-microsoft-prod.deb

  - name: aws-cli
    before: 
      cd /workspace;   
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      sudo ./aws/install; 
      cd $THEIA_WORKSPACE_ROOT; 
