#! /bin/bash

# set -e 
echo "--- Deleting Object(s) ---"

# Taking an argument
if [ -z "$1"]; then
    echo "Kindly provide a bucket name as an argument to the command"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json



aws s3api delete-objects --bucket $BUCKET_NAME

