#! /bin/bash

set -e 

OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove the file of they already exist
rm -r $OUTPUT_DIR


mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; $NUM_FILES; i++)); do
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2> /dev/null

done

echo "Done."


tree $OUTPUT_DIR